[environment_variables]
EXAMPLE_VARIABLE = "example_value"
ANOTHER_VARIABLE = 42

[postgres_variables]
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_HOST = "postgres"
POSTGRES_DB = "postgres"
POSTGRES_PORT = 5432